CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, name TEXT, role TEXT DEFAULT 'citizen', points INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, type TEXT, description TEXT, x REAL, y REAL, zone TEXT, photo TEXT, status TEXT DEFAULT 'Received', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pickups(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, zone TEXT, waste_type TEXT, date TEXT, status TEXT DEFAULT 'Booked');
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, message TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS rewards(id INTEGER PRIMARY KEY, name TEXT, cost INTEGER);
INSERT OR IGNORE INTO users(id,name) VALUES(1,'Demo Student');
INSERT OR IGNORE INTO rewards VALUES(1,'Canteen coupon Rs20',50),(2,'Notebook',80),(3,'Reusable bottle',150),(4,'Plant sapling',40);
